name: Deploy
on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - name: Run update script
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: sudo /opt/moodle/update.sh